<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpySlice02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

# Create a 1D array 'arr' with values from 30 up to (but not including) 41
# Output: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
arr = np.arange(30, 41)
print('\n Content of Array arr \n', arr)

# Create 'arr1' as a full slice of 'arr' (from start to end)
# Using [::] effectively creates a view of the entire original array
arr1 = arr[::]
print('\n Content of Array arr1 \n', arr1)

# Create 'arr2' by reversing the entire array
# Syntax: [-1::-1] starts at the last element and moves backward to the start
# Output: [40, 39, 38, ..., 30]
arr2 = arr[-1::-1]
print('\n Content of Array arr2 \n', arr2)

# Create 'arr3' by slicing from the start up to (but not including) the last 5 elements
# This removes the last 5 items from the view
arr3 = arr[:-5:]
print('\n Content of Array arr3 \n', arr3)




 Content of Array  arr  
 [30 31 32 33 34 35 36 37 38 39 40]

 Content of Array  arr1  
 [30 31 32 33 34 35 36 37 38 39 40]

 Content of Array  arr2 
 [40 39 38 37 36 35 34 33 32 31 30]

 Content of Array  arr3 
 [30 31 32 33 34 35]
