<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyArray04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Import the numpy library and alias it as 'np' for convenience
import numpy as np

# Create a numpy array 'arr1' containing the integers 10 through 90 in increments of 10
arr1 = np.array([10, 20, 30, 40, 50, 60 , 70, 80 , 90])

# Print a newline, followed by the string "This is content of array arr1", another newline, and then the contents of the array
print('\n  This is content of array arr1 \n' , arr1)

# Create a new numpy array 'arr2' by passing 'arr1' to np.array(), which creates a copy of the array
arr2 =np.array(arr1)

# Print a newline, followed by the string "This is content of array arr2", another newline, and then the contents of the array (note: there are extra spaces in the string)
print('\n  This is content of array  arr2 \n' , arr2)

# Assign 'arr3' to reference the same array as 'arr2' (no new copy is created)
arr3 = arr2

# Print a newline, followed by the string "This is content of array arr3", another newline, and then the contents of the array
print('\n  This is content of array  arr3 \n' , arr3)


  This is content of array arr1 
 [10 20 30 40 50 60 70 80 90]

  This is content of array  arr2 
 [10 20 30 40 50 60 70 80 90]

  This is content of array  arr3 
 [10 20 30 40 50 60 70 80 90]
