<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyArrayDtypeNbytes01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

# --- 1D ARRAY SECTION ---
# Create a 1D NumPy array (vector) containing 10 integers
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

print('\n Dimension of array 1 is  ', arr1.ndim)      # ndim: Number of axes (1 for 1D)
print('\n Size  of array 1 is   ', arr1.size)        # size: Total number of elements
print('\n Shape  of array 1 is   ', arr1.shape)      # shape: Tuple showing length along each axis
print('\n Item Size of element of array arr1 ', arr1.itemsize) # Size of ONE element in bytes
print('\n Data type of elements of array arr1 ', arr1.dtype)   # The internal data type (e.g., int64)
print('\n Total bytes consumed by arr1 ', arr1.nbytes)        # total bytes = size * itemsize
print('\n Content of array arr1 \n' , arr1)



# --- 2D ARRAY SECTION ---
# Create a 2D array (matrix) with 2 rows and 5 columns
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print('\n Dimension of array 2 is ', arr2.ndim)       # 2D array has 2 axes (rows, columns)
print('\n Size  of array 2 is   ', arr2.size)        # Total elements: 10
print('\n Shape  of array 2 is   ', arr2.shape)      # Returns (2, 5)
print('\n Item Size of element of array arr2 ', arr2.itemsize)
print('\n Data type of elements of array arr2 ', arr2.dtype)
print('\n Total bytes consumed by arr2 ', arr2.nbytes)
print('\n Content of array arr2 \n' , arr2)


# --- 3D ARRAY SECTION ---
# Create a 3D array (tensor) with shape (2, 2, 3)
# Structure: 2 "pages", each containing a 2x3 matrix
arr3 = np.array([[[10,20,30],[40, 50, 60]],[[70, 80, 90] ,[100 , 110, 120]]])

print('\n Dimension of array 3 is   ', arr3.ndim)     # 3D array has 3 axes
print('\n Size  of array 3 is   ', arr3.size)        # Total elements: 12
print('\n Shape  of array 3 is   ', arr3.shape)      # Returns (2, 2, 3)
print('\n Item Size of element of array arr3 ', arr3.itemsize)
print('\n Data type of elements of array arr3 ', arr3.dtype)
print('\n Total bytes consumed by arr3 ', arr3.nbytes)
print('\n Content of array arr3 \n' , arr3)


 Dimension of array 1 is   1

 Size  of array 1 is   10

 Shape  of array 1 is   (10,)

 Item Size of element of array arr1  8

 Data type  of element of array arr1  int64

 Total bytes consumed by eleement of array arr1  80

 Content of array arr1 
 [ 1  2  3  4  5  6  7  8  9 10]

 Dimension of array 2 is  2

 Size  of array 2 is   10

 Shape  of array 2 is   (2, 5)

 Item Size of element of array arr2  8

 Data type  of element of array arr2  int64

 Total bytes consumed by eleement of array arr2  80

 Content of array arr2 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

 Dimension of array 3 is   3

 Size  of array 3 is   12

 Shape  of array 3 is   (2, 2, 3)

 Item Size of element of array arr3  8

 Data type  of element of array arr3  int64

 Total bytes consumed by eleement of array arr3  96

 Content of array arr3 
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
