<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyArrayNdim01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import the NumPy library, which is used for creating and manipulating arrays
import numpy as np

# Create a 1D NumPy array with integers from 1 to 8 and 10
arr1 = np.array([1,2,3,4,5,6,7,8,10])

# Print the number of dimensions (ndim) of arr1; for a 1D array, this should be 1
print('\n Dimeshan of array 1 is  \n', arr1.ndim)
# Print the contents of arr1
print('\n Content of array arr1 \n' , arr1)


# Create a 2D NumPy array with two rows: first row [10,20,30,40,50], second row [60,70,80,90,100]
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
# Print the number of dimensions (ndim) of arr2; for a 2D array, this should be 2
print('\n Dimeshan of array 2 is  \n', arr2.ndim)
# Print the contents of arr2
print('\n Content of array arr2 \n' , arr2)


# Create a 3D NumPy array with shape (2, 2, 3): two 2x3 matrices stacked
arr3 = np.array([[[10,20,30],[40, 50, 60]],[[70, 80, 90] ,[100 , 110, 120]]])
# Print the number of dimensions (ndim) of arr3; for a 3D array, this should be 3
print('\n Dimeshan of array 3 is  \n', arr3.ndim)
# Print the contents of arr3
print('\n Content of array arr3 \n' , arr3)




 Dimeshan of array 1 is  
 1

 Content of array arr1 
 [ 1  2  3  4  5  6  7  8 10]

 Dimeshan of array 2 is  
 2

 Content of array arr2 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

 Dimeshan of array 3 is  
 3

 Content of array arr3 
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
