<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyMatrix02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# Import the NumPy library for numerical computations and array operations
import numpy as np

# Create a 3x3 NumPy array with the given values
mat = np.array([[20,10,40],[90,80,30],[15,5,25]])

# Sort the array in the default manner (flattens the array and sorts all elements)
mat2 = np.sort(mat)

# Print the content of the sorted array mat2 with a descriptive header
print('\n Content of Matrix mat2 ' , mat2)

# Sort the array along axis=1 (sorts each row individually)
mat3 = np.sort(mat, axis=1)

# Print the content of mat3 with a descriptive header
print('\n Content of Matrix mat3 ' , mat3)

# Sort the array along axis=0 (sorts each column individually)
mat4 = np.sort(mat, axis=0)

# Print the content of mat4 with a descriptive header
print('\n Content of Matrix mat4 ' , mat4)


 Content of Matrix mat2  [[10 20 40]
 [30 80 90]
 [ 5 15 25]]

 Content of Matrix mat3  [[10 20 40]
 [30 80 90]
 [ 5 15 25]]

 Content of Matrix mat4  [[15  5 25]
 [20 10 30]
 [90 80 40]]
