<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/Numpyones01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
# Import the NumPy library, which is used for numerical computations and array operations.
import numpy as np

# Create a 1D array of 4 elements, all initialized to one.
# By default, the data type (dtype) is float64, so the elements are floating-point numbers.
a = np.ones(4)

# Print the array 'a'. It will display as [1. 1. 1. 1.] to indicate floats.
print(a)

# Create a 1D array of 4 elements, all initialized to one, with dtype set to int (integer).
# This uses integer ones instead of floats.
b = np.ones(4, int)

# Print the array 'b'. It will display as [1 1 1 1] without decimals, as they are integers.
print(b)

# Create a 1D array of 4 elements, all initialized to one, with dtype set to float (float64).
# This is similar to 'a', explicitly specifying the float dtype.
c = np.ones(4, float)

# Print the array 'c'. It will display as [1. 1. 1. 1.], same as 'a'.
print(c)

# Create a 2D array of shape (3, 4) with all elements initialized to one.
# Default dtype is float64.
d = np.ones((3, 4))

# Print a header followed by the array 'd'. It will show a 3x4 matrix of 1.0 floats.
print('\n The Content of 2D Array d \n', d)

[1. 1. 1. 1.]
[1 1 1 1]
[1. 1. 1. 1.]

 The Content of 2D Array d 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
