<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyMatrix03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
# Import the NumPy library for numerical computations and matrix operations
import numpy as np

# Create first 3x3 matrix
mat1 = np.matrix([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# Create second 3x3 matrix
mat2 = np.matrix([[5, 15, 25],
                  [35, 45, 55],
                  [65, 75, 85]])

# Add both matrices (element-wise addition)
# Since both matrices are 3x3, addition is valid
mat3 = mat1 + mat2

# Display the result of matrix addition
print('\nContent of matrix mat3 (Addition Result):\n', mat3)


# Create a 2x3 matrix
mat11 = np.matrix([[5, 10, 15],
                   [15, 35, 45]])

# Create a 3x2 matrix
mat12 = np.matrix([[2, 3],
                   [4, 5],
                   [6, 7]])

# Multiply the matrices
# Matrix multiplication rule:
# (rows × columns) → (2x3) × (3x2) = (2x2)
# Number of columns in first matrix must equal number of rows in second matrix
mat13 = mat11 * mat12

# Display the result of matrix multiplication
print('\nContent of matrix mat13 (Multiplication Result):\n', mat13)



Content of matrix mat3 (Addition Result):
 [[ 15  35  55]
 [ 75  95 115]
 [135 155 175]]

Content of matrix mat13 (Multiplication Result):
 [[140 170]
 [440 535]]
