<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/Numpyzero01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
# Import the NumPy library, which is used for numerical computations and array operations.
import numpy as np

# Create a 1D array of 5 elements, all initialized to zero.
# By default, the data type (dtype) is float64, so the elements are floating-point numbers.
a = np.zeros(5)

# Print the array 'a'. It will display as [0. 0. 0. 0. 0.] to indicate floats.
print(a)

# Create a 1D array of 5 elements, all initialized to zero, with dtype set to int (integer).
# This uses integer zeros instead of floats.
b = np.zeros(5, int)

# Print the array 'b'. It will display as [0 0 0 0 0] without decimals, as they are integers.
print(b)

# Create a 1D array of 5 elements, all initialized to zero, with dtype set to float (float64).
# This is similar to 'a', explicitly specifying the float dtype.
c = np.zeros(5, float)

# Print the array 'c'. It will display as [0. 0. 0. 0. 0.], same as 'a'.
print(c)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]
