<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/Numpyzero02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
# Import the NumPy library for array operations.
import numpy as np

# Create a 2D array of shape (3, 4) with all elements initialized to zero.
# Default dtype is float64.
a = np.zeros((3, 4))

# Print the array 'a'. It will show a 3x4 matrix of 0.0 floats.
print(a)

# Create a 2D array of shape (3, 4) with integer zeros.
b = np.zeros((3, 4), int)

# Print the array 'b'. It will show a 3x4 matrix of 0 integers.
print(b)

# Create a 2D array of shape (3, 4) with float zeros (explicit dtype).
c = np.zeros((3, 4), float)

# Print the array 'c'. Similar to 'a', a 3x4 matrix of 0.0 floats.
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
