<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyMatrix01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Import the NumPy library, which is used for numerical computations and array operations
import numpy as np

# Create a 1x3 matrix using a list of integers
mat = np.matrix([10, 20, 30])

# Print the content of the matrix 'mat' with a descriptive header
print('\n Content of Matrix mat \n',mat)

# Create a 2x3 matrix using a list of lists
mat2 = np.matrix([[10, 20, 30], [40, 50, 60]])

# Print a header for mat2
print('\n Content of mat2 \n')
# Print the content of mat2
print(mat2)

# Find the maximum value in mat2
ma= mat2.max()

# Print the maximum value with a descriptive header
print('\n Maximum  value of  the matrix \n ',ma)

# Find the minimum value in mat2
mi= mat2.min()

# Print the minimum value with a descriptive header (note: typo in "Mainuma" should be "Minimum")
print('\n Mainuma value of  the matrix \n ',mi)

# Calculate the sum of all elements in mat2
su = mat2.sum()
# Print the sum with a descriptive header
print('\n Sum of element of  matrix \n ',su)

# Calculate the mean (average) of all elements in mat2
me = mat2.mean()
# Print the mean with a descriptive header (note: typo in "Avearge" should be "Average")
print('\n Avearge  of element of  matrix \n ',me)

# Create a 3x4 matrix using np.arange to generate numbers 0-11 and reshape them
mat3 = np.arange(12).reshape(3,4)
# Print the content of mat3 with a descriptive header (note: typo in "mat 3" with extra space)
print('\n Content of mat 3 is \n', mat3)


 Content of Matrix mat 
 [[10 20 30]]

 Content of mat2 

[[10 20 30]
 [40 50 60]]

 Maximum  value of  the matrix 
  60

 Mainuma value of  the matrix 
  10

 Sum of element of  matrix 
  210

 Avearge  of element of  matrix 
  35.0

 Content of mat 3 is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
