<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyMathOperation01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import the NumPy library and alias it as 'np' for easier typing
import numpy as np

# Create a 1D NumPy array containing five integers
a = np.array([10, 20, 30, 40, -45])

# Display the original array
print('\n Content of Array A \n' , a)

# Scalar Addition: Adds 5 to every single element in the array
b = a + 5
print('\n Content of Array B \n' , b)

# Scalar Multiplication: Multiplies every element in the array by 5
c = a * 5
print('\n Content of Array C \n' , c)

# Scalar Division: Divides every element in the array by 2
# Note: In Python 3, this will return float values (e.g., 10 becomes 5.0)
d = a / 2
print('\n Content of Array D \n' , d)


 Content of Array A 
 [ 10  20  30  40 -45]

 Content of Array B 
 [ 15  25  35  45 -40]

 Content of Array C 
 [  50  100  150  200 -225]

 Content of Array D 
 [  5.   10.   15.   20.  -22.5]
