<a href="https://colab.research.google.com/github/Triveni18/Python/blob/main/NumPy/NumpyArraySize01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Import the NumPy library, which is used for creating and manipulating arrays
import numpy as np

# Create a 1D NumPy array with integers from 1 to 10
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

# Print the number of dimensions (ndim) of arr1; for a 1D array, this should be 1
print('\n Dimension of array 1 is  ', arr1.ndim)

# Print the total number of elements (size) in arr1; for this array, it should be 10
print('\n Size  of array 1 is  ', arr1.size)
# Print the shape of arr1; for a 1D array of 10 elements, this should be (10,)
print('\n Shape  of array 1 is  ', arr1.shape)
# Print the contents of arr1
print('\n Content of array arr1 \n' , arr1)


# Create a 2D NumPy array with two rows: first row [10,20,30,40,50], second row [60,70,80,90,100]
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
# Print the number of dimensions (ndim) of arr2; for a 2D array, this should be 2
print('\n Dimension of array 2 is ', arr2.ndim)

# Print the total number of elements (size) in arr2; for this array, it should be 10
print('\n Size  of array 2 is  ', arr2.size)
# Print the shape of arr2; for this array, it should be (2, 5)
print('\n Shape  of array 2 is  ', arr2.shape)
# Print the contents of arr2
print('\n Content of array arr2 \n' , arr2)


# Create a 3D NumPy array with shape (2, 2, 3): two 2x3 matrices stacked
arr3 = np.array([[[10,20,30],[40, 50, 60]],[[70, 80, 90] ,[100 , 110, 120]]])
# Print the number of dimensions (ndim) of arr3; for a 3D array, this should be 3
print('\n Dimension of array 3 is  ', arr3.ndim)
# Print the total number of elements (size) in arr3; for this array, it should be 12
print('\n Size  of array 3 is  ', arr3.size)
# Print the shape of arr3; for this array, it should be (2, 2, 3)
print('\n Shape  of array 3 is  ', arr3.shape)
# Print the contents of arr3
print('\n Content of array arr3 \n' , arr3)



 Dimension of array 1 is   1

 Size  of array 1 is   10

 Shape  of array 1 is   (10,)

 Content of array arr1 
 [ 1  2  3  4  5  6  7  8  9 10]

 Dimension of array 2 is  2

 Size  of array 2 is   10

 Shape  of array 2 is   (2, 5)

 Content of array arr2 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

 Dimension of array 3 is   3

 Size  of array 3 is   12

 Shape  of array 3 is   (2, 2, 3)

 Content of array arr3 
 [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
